### ISSUE TITLE
Conceal replacing symbols with '?'

### ISSUE THREAD

**Issue by tarzanjunior** [KeitaNakamura/tex-conceal.vim#12]
![Screen Shot 2020-03-25 at 3 07 46 PM](https://user-images.githubusercontent.com/25302192/77522689-a336e180-6eaa-11ea-93d5-76379df78d76.png)
This is what it shows, it apparently replaces expressions of type a_n by '?'.
But I don't think this should be the case since my vimrc looks like this:
![Screen Shot 2020-03-25 at 3 15 55 PM](https://user-images.githubusercontent.com/25302192/77523313-923aa000-6eab-11ea-8762-9bc17cc6f632.png)

the let g:tex_conceal='abdmg' should mean that the subscripts , etc should not be concealed, but they are.

I also tried \mathscr{F} with conceal and ? in a box is shown.

**Comment by ChasingZenith** [comment]
I have the same issue too, and I doubt that this is because I haven't chosen the right font. Is there any recommended font that is suitable for conceal function for latex?

I check /usr/share/vim/vim81/syntax/tex.vim and find that I can't make subscript 'hklmnpst' show up correctly.

**Comment by ChasingZenith** [comment]
#17 gives a font that can deal with this question mark problem.

Thanks to @KeitaNakamura.
> DejaVu font supports the character n (see U+2099 in Unicode characters supported by the DejaVu )
