### ISSUE TITLE
g:tex_subscripts will not affect when X_{n}

### ISSUE THREAD

**Issue by ChasingZenith** [KeitaNakamura/tex-conceal.vim#17]
Since I don't know if there is a font that can support subscript "hklmnpst", I want to not conceal this character.

So I do what `:h tex-conceal` give and
```vim
let g:tex_subscripts= "[0-9aeijoruvx,+-/().]"
```
but this doesn't work. I hope this plugin can also be configured using this variable.

Currently, my workaround is to run
```vim
...
syn match texMathSymbol '_\%(n\|{\s*n\s*}\)' contained conceal cchar=n
... etc ...
```
after I open a tex file.

**Comment by KeitaNakamura** [comment]
Thanks for reporting. Yes, the feature you suggested should be implemented in this plugin. Could you make PR?

DejaVu font supports this font (see `U+2099` in [Unicode characters supported by the DejaVu ](https://www.fileformat.info/info/unicode/font/dejavu_sans/list.htm))

**Comment by ChasingZenith** [comment]
I hope that I can help. But I am not very familiar with vim script and I don't know where is this tex.vim plugin locate in the vim filesystem.

**Comment by xingbo92** [comment]
After the recent update, the option to not conceal super/subscript doesn't seem to work anymore. Regardless of the tex-conceal setting, the super/subscripts are concealed
