### ISSUE TITLE
Using `$` for maths

### ISSUE THREAD

**Issue by twsh** [KeitaNakamura/tex-conceal.vim#31]
I get different results when I have, e.g., `\(\langle 1 \rangle\)` and `$\langle 1 \rangle$`. The former is fine, but the latter doesn't conceal the `\rangle`. If I add a space between it and the `$` it does. Shouldn't they both be concealed the same?

I want to use `$`, because I write in Pandoc's markdown which uses them to mark maths written in LaTeX.

**Comment by Konfekt** [comment]
Does this perhaps hinge on the additional `\s*` in 

https://github.com/KeitaNakamura/tex-conceal.vim/blob/e241efcad90440532c7f83af2e247723d341d67a/after/syntax/tex.vim#L15

**Comment by KeitaNakamura** [comment]
In my vim, both works fine. Could someone reproduce this?
