### ISSUE TITLE
how to set the color of conceal

### ISSUE THREAD

**Issue by Crack-Hu** [KeitaNakamura/tex-conceal.vim#36]
![Screenshot_20210216_233606_1](https://user-images.githubusercontent.com/78095095/108085136-f7911400-70af-11eb-9fef-58595ec6f41e.png)
when I set the background of vim to black, it's terrible because the conceal shows the text in black too, so I wonder to change the color of conceal, thanks.

**Comment by Crack-Hu** [comment]
the problem may cause by the plug 'indentline'

**Comment by KeitaNakamura** [comment]
Since [indentLine](https://github.com/Yggdroot/indentLine) defines the conceal color, it could cause problems.
I think you should not load indentLine for tex file by on-demand loading ([example](https://github.com/junegunn/vim-plug#plug-options)).
