### ISSUE TITLE
Can't set the background color of replaced characters

### ISSUE THREAD

**Issue by sshwy** [KeitaNakamura/tex-conceal.vim#4]
I'm trying to change the background color of replaced characters because I want it to be the same as the background color of my terminal. (The background of my terminal is black, but the background of replaced characters is grey)

How to change it?

**Comment by miguelraz** [comment]
Same issue here. Bump!

**Comment by KevinNadaud** [comment]
I found a way to remove the conceal highlight, you can add into your .vimrc the following lines:
````
hi Conceal ctermbg=NONE
hi Conceal ctermfg=NONE
hi Conceal guifg=NONE
hi Conceal guibg=NONE
````

**Comment by sshwy** [comment]
Thanks! Problem solved!
