### ISSUE TITLE
The symbol doesn't appear properly

### ISSUE THREAD

**Issue by zhuosongz** [KeitaNakamura/tex-conceal.vim#5]
Hi, 

I have one issue about the appearance of the wide symbols. For example, when I input 
\begin{align*}
    \mathscr{F} ( \bm{\tau}, \alpha) 
\end{align*}
it becomes
![image](https://user-images.githubusercontent.com/31466564/57194244-ff89cd80-6f87-11e9-8183-0b1b02dcec75.png)
Could you please help me with it? Thank you a lot!

Best, 
Mathieu

**Comment by moreka** [comment]
I also have the same issue, but for me the symbols are shown pretty much small. I guess it depends on which font you use, which in my case is InconsolataGo Nerd Font.

**Comment by KeitaNakamura** [comment]
Yes, I think this is a problem related with your font.
Actually, I also need to put the white space between `\mathscr{F}` and `(\bm{\tau}, \alpha)` to get good appearance.
For example, in my environment, `$\mathscr{F} (\bm{\alpha}, \bm{\tau})$` becomes

<img width="95" alt="Screen Shot 2020-03-17 at 13 31 09" src="https://user-images.githubusercontent.com/16015926/76822273-d8f91c00-6853-11ea-8ef6-9b44a12a58c8.png">

where upper has no white space.
