### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by kostaskonkk** [KeitaNakamura/tex-conceal.vim#6]
Trying to install the plugin with plug.vim, I get fatal: could not read Username. Does anyone have any idea what I can do to solve this issue?
Searching online says that usually the name is not written correctly, but I have copied and pasted the name, so this cannot be an issue. I believe it is associated with the '.' in the repository name.

**Comment by KeitaNakamura** [comment]
I think this is a problem related with your Github setup, not this plug-in.

Following can be help:
* https://stackoverflow.com/questions/22147574/fatal-could-not-read-username-for-https-github-com-no-such-file-or-directo

Thanks
