### ISSUE TITLE
What is "b"

### ISSUE THREAD

**Issue by Zackhardtoname** [KeitaNakamura/tex-conceal.vim#7]
I am trying to understand the recommended setting. The [vim doc](http://vimdoc.sourceforge.net/htmldoc/syntax.html) says among the options:

> 	a = accents/ligatures
	d = delimiters
	m = math symbols
	g = Greek
	s = superscripts/subscripts

What is b in our case? Also, we don't have 's', but it looks like superscripts/subscripts are concealed anyway? Sorry if I have missed something.

**Comment by JoostScheffer** [comment]
b stands for **bold** i believe

**Comment by Zackhardtoname** [comment]
Oh gotcha. Thanks!
