### ISSUE TITLE
I can't seem to figure out how to show ligatures in gvim

### ISSUE THREAD

**Issue by JoostScheffer** [KeitaNakamura/tex-conceal.vim#8]
I am trying to display ligatures in my gvim text editor window.
I am using VimTeX and have added the following code to my vim.rc file:

```
call plug#begin('~/.vim/plugged')

Plug 'lervag/vimtex'
let g:tex_flavor='latex'
let g:tex_DefoalTargetFormat = 'pdf'
let g:tex_MultipleCompileFormats = 'pdf,aux'

let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_options 
	\ = '-reuse-instance -forward-search @tex @line @pdf'
let g:vimtex_vview_general_options_latexmk = '-reuse-instance'

Plug 'sirver/ultisnips'
let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'

behave xterm

setlocal spell
set spelllang=nl,en_gb
inoremap <C-l> <c-g>u<Esc>[s1z=`]a<c-g>u

Plug 'KeitaNakamura/tex-conceal.vim', {'for': 'tex'}
let g:vimtex_quickfix_mode=2
set conceallevel=2
let g:tex_conceal='abdmgs'
let g:tex_fast="bcmMprsSvV"

call plug#end()
```

Yet no ligates show when i open gvim to work om some files.

![image](https://user-images.githubusercontent.com/56606926/76662091-559ea880-657d-11ea-8cb8-3a924fbf8f7f.png)

Like visible above, I use the Consolas font. Also I use the utf-8 encoding and the directx renderoption.

Does someone know what is wrong with my setup?

**Comment by JoostScheffer** [comment]
I fixed it by placing the last non-plug part of my code after the `call plug#end()` and adding 

```
set encoding=utf-8
set renderoptions=type:directx
```
in the vimrc file.

***

Although the ligates now show up i cant say that i am satisfied with the result.
Now the syntax has a white transparent block placed on top of the syntax. 

![image](https://user-images.githubusercontent.com/56606926/76662942-c8108800-657f-11ea-961b-307bf754c0ec.png)

Would someone perhaps know a way out?

**Comment by KeitaNakamura** [comment]
Could you try this #4?
